server:
  port: 8080
  servlet:
    context-path: /mightyjava
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mightyjava?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: dialect:org.hibernate.dialect.MySQL5Dialect
  mvc:
    view:
      prefix: /view/
      suffix: .jsp